url: https://fullbright.github.io
#baseurl: /bible-latex-site/
#baseurl: /

# Site settings
title: A Bible typeset for study
email: full3right@gmail.com
description: "Ever needed a Bible for study notes taking ? We typeset one with margins for you. Available for download !"


# Team names, titles and social links
people:
- name: Full Bright
  pic: 1
  position: Developper, typeset in Latex
  social:
    - title: twitter
      url: http://twitter.com/t0o1
    - title: facebook
      url: fb.me/brightsoftwares
    - title: stack-overflow
      url: #

- name: Sergio Afanou
  pic: 2
  position: Developper, references
  social:
    - title: twitter
      url: http://twitter.com/t0o1
    - title: facebook
      url: fb.me/sergio.afanou
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/t0o1
  - title: facebook
    url: http://fb.me/brightsoftwares
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: http://github.com/fullbright/bible

# Postal address (add as many lines as necessary)
address:
  - line: 31 rue Daniel Toussaint
  - line: 94460 Valeton

# Build settings
markdown: kramdown
permalink: pretty
#theme: jekyll-theme-cayman
